#!/bin/bash

set -e

hex()
{
	/usr/bin/openssl rand -hex 8
}

echo "Preparing container .."
COMMAND="/bin/shellinaboxd --debug --no-beep -u shellinabox -g shellinabox -c /var/lib/shellinabox -p ${SIAB_PORT} --user-css ${SIAB_USERCSS}"

if [ "$SIAB_PKGS" != "none" ]; then
	set +e
	apk add --update $SIAB_PKGS
	rm -rf /var/cache/apk/*
	set -e
fi

if [ "$SIAB_SSL" != "true" ]; then
	COMMAND+=" -t"
fi

if [ "${SIAB_ADDUSER}" == "true" ]; then
	sudo=""
	if [ "${SIAB_SUDO}" == "true" ]; then
		sudo="-G sudo"
	fi
	/usr/sbin/addgroup -g ${SIAB_GROUPID} ${SIAB_GROUP}
        if [ -d ${SIAB_HOME} ]; then
		/usr/sbin/adduser -u ${SIAB_USERID} -G ${SIAB_GROUP} ${sudo} -s ${SIAB_SHELL} -h ${SIAB_HOME} -H -D ${SIAB_USER}
	else
		/usr/sbin/adduser -u ${SIAB_USERID} -G ${SIAB_GROUP} ${sudo} -s ${SIAB_SHELL} -h ${SIAB_HOME} -D ${SIAB_USER}
	fi
	if [ "${SIAB_PASSWORD}" == "putsafepasswordhere" ]; then
		SIAB_PASSWORD=$(hex)
		echo "Autogenerated password for user ${SIAB_USER}: ${SIAB_PASSWORD}"
	fi
	echo "${SIAB_USER}:${SIAB_PASSWORD}" | /usr/sbin/chpasswd
	unset SIAB_PASSWORD
fi

for service in ${SIAB_SERVICE}; do
	COMMAND+=" -s ${service}"
done

if [ "$SIAB_SCRIPT" != "none" ]; then
	set +e
	/usr/bin/curl -s -k ${SIAB_SCRIPT} > /prep.sh
	chmod +x /prep.sh
	echo "Running ${SIAB_SCRIPT} .."
	/prep.sh
	set -e
fi

echo "Starting container .."
if [ "$@" = "shellinabox" ]; then
	echo "Executing: ${COMMAND}"
	exec ${COMMAND}
else
	echo "Not executing: ${COMMAND}"
	echo "Executing: ${@}"
	exec $@
fi
